
### Send POST request with json body
POST http://localhost:8000/api/votings
Content-Type: application/json

{
  "name": "Some Body Oce told me",
  "polls": [
    {
      "name": "String",
      "description": ""
    }
  ]
}


###

# Get All Votings
GET http://localhost:8000/api/votings
Accept: application/json

###

# Get All Votings
GET http://localhost:8000/api/voting/voring_id2
Accept: application/json

###
