# A documentation for this http client can be found at https://marketplace.visualstudio.com/items?itemName=humao.rest-client

# Create a voting with two polls
# @name create_votings
POST http://localhost:8000/api/votings
Content-Type: application/json
Accept: application/json

{
  "name": "Some Body Oce told me",
  "polls": [
    {
      "name": "test poll 1",
      "description": "String description"
    },
    {
      "name": "test poll 2",
      "description": "String description"
    }
  ]
}

###

# Get The created voting
GET http://localhost:8000/api/votings/{{create_votings.response.body.$.votingId}}
Content-Type: application/json
Accept: application/json
Authorization: {{create_votings.response.body.$.adminKey}}

###

# Set the active poll
PUT http://localhost:8000/api/votings/{{create_votings.response.body.$.votingId}}/polls/active
Content-Type: application/json
Accept: application/json
Authorization: {{create_votings.response.body.$.adminKey}}

{
  "pollIndex": 1
}


###

# Create a voter
# @name create_voter
POST http://localhost:8000/api/votings/{{create_votings.response.body.$.votingId}}/voters
Content-Type: application/json
Accept: application/json
Authorization: {{create_votings.response.body.$.adminKey}}

{
  "username": "Donato Potato"
}

###

# Get the active poll
GET http://localhost:8000/api/votings/{{create_voter.response.body.$.votingId}}/polls/active
Accept: application/json
Authorization: {{create_voter.response.body.$.voterKey}}

###

# Get info for authenticated user
GET http://localhost:8000/api/votings/{{create_votings.response.body.$.votingId}}/voters/info
Accept: application/json
Authorization: {{create_voter.response.body.$.voterKey}}

###

# Set the active poll
PUT http://localhost:8000/api/votings/{{create_votings.response.body.$.votingId}}/polls/0/vote
Content-Type: application/json
Accept: application/json
Authorization: {{create_voter.response.body.$.voterKey}}

{
  "answer": true
}

